[package]
name = "boring_os"
version = "0.1.0"
authors= ["Oliver Geller <oliver.geller@rochester.edu>"]

[dependencies]
rlibc = "1.0"
volatile = "0.2.3"
spin = "0.4.5"
multiboot2 = "0.3.2"
bitflags = "0.9.1"
x86_64 = "0.1.2"


[lib]
crate-type = ["staticlib"]
path = "kernel/lib.rs"
