[package]
name = "boring_os"
version = "0.1.0"
authors= ["Oliver Geller <oliver.geller@rochester.edu>"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"


[lib]
crate-type = ["staticlib"]
path = "kernel/lib.rs"
