[package]
name = "mkinitramfs"
version = "0.1.0"
authors = ["aticu <15schnic@gmail.com>"]
description = "The initramfs creator of BoringOS."
keywords = ["OS", "operating", "system", "BoringOS", "std"]
license = "MIT"

[dependencies]
byteorder = "1.1.0"
